name: Build HA add-on

on:
  push:
    branches:
      - main
    tags:
      - "*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-app:
    name: Build add-on
    uses: ./.github/workflows/build-app.yaml
    with:
      app: plants
      publish: true
    secrets: inherit
